### ISSUE TITLE
The result does not match the paper report？

### ISSUE THREAD

**Issue by buglesxu** [yumeng5/WeSHClass#3]
May I ask where I made a mistake?
dataset nyt，doc：
Iter 3750:
Number of blocked documents back to level 1: 343
f1_macro = 0.50912, f1_micro = 0.66738 @ level 1
f1_macro = 0.38865, f1_micro = 0.58124 @ level 2
f1_macro = 0.4086, f1_micro = 0.6319 @ all classes
Fraction of documents with label changes: 0.099 %

Fraction: 0.099 % < tol: 0.1 %
Reached tolerance threshold. Self-training terminated.
Final model saved to: ./results/nyt/docs/level_1/final.h5
Self-training time: 13302.54s
Classification results are written in ./nyt/out.txt

But the paper：f1_macro、f1_micro = 0.532、0.827？

**Comment by yumeng5** [comment]
Hi @buglesxu,

Sorry for my late response. Could you share how you set the command line arguments (if their default values are not used)? Also, you may check the self-training logs under `results/nyt/docs` (different levels have separate logs); if your logs showed better results in the middle of self-training and then the performance dropped, probably you could try to set a smaller value of `--maxiter` and/or a bigger value of `--delta` to terminate self-training earlier.

Thanks,
Yu

**Comment by buglesxu** [comment]
@yumeng5 Thank you very much for your detailed reply！！
I run the code follow the method in Quick Start, did not use else arguments. I check the self-training logs, it showed better results in the middle of self-training. the middle result can be 0.72/0.84，I'm not sure the paper' result refer to f1_macro/f1_micro@ all classes?

**Comment by yumeng5** [comment]
Hi @buglesxu ,

Thanks for the information. Then the default command-line arguments should give similar results in the paper. I guess you also set `--gamma` smaller than `1.0` (which is correct for the `nyt` dataset) since I saw that your results showed documents were blocked at the higher level. And the self-training process indeed may have some randomness (i.e., sometimes the performance may drop significantly if the self-training is not terminated earlier). Therefore, it would be favorable in practice to have a small development set to monitor the self-training process (when to terminate it appropriately). As for the reported results in the paper, yes they were f1 scores for all classes.

Best,
Yu

**Comment by buglesxu** [comment]
@yumeng5 
I run the ./test.sh,  dataset nyt，keywords：
Iter 2670:
Number of blocked documents back to level 1: 913
f1_macro = 0.87436, f1_micro = 0.93831 @ level 1
f1_macro = 0.63889, f1_micro = 0.83389 @ level 2
f1_macro = 0.67782, f1_micro = 0.8902 @ all classes
Fraction of documents with label changes: 0.107 %

Iter 2700:
Number of blocked documents back to level 1: 911
f1_macro = 0.87462, f1_micro = 0.93838 @ level 1
f1_macro = 0.63928, f1_micro = 0.83399 @ level 2
f1_macro = 0.67816, f1_micro = 0.89029 @ all classes
Fraction of documents with label changes: 0.092 %
It means the result is better than the reported results in the paper(0.632/0.874)?
Thanks,
Bu

**Comment by yumeng5** [comment]
Hi @buglesxu ,

Yes, the results you got were slightly better than those reported in the paper; the training process does have some randomness and it's possible to obtain better results.

Best,
Yu
